# Generated by Django 3.2.9 on 2021-11-24 15:35

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(verbose_name='url')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='mainstoreapp.category', verbose_name='Связи/ Категория/ Подкатегория')),
            ],
            options={
                'verbose_name': 'Категория(ю)',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CompatibleParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название совместимой модели')),
            ],
            options={
                'verbose_name': 'Совместимость',
                'verbose_name_plural': 'Совместимости',
            },
        ),
        migrations.CreateModel(
            name='FixedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Постов/ы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано?')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('old_price', models.IntegerField(blank=True, help_text='Поле для отображения старой цена. Для заполнения не обязательно. В случае если\n        цена на товар снижена, указать сюда старую цена а поле "Цена" указать новую, в таком случае на сайте старый \n        ценник будет перечеркнут. В случае если цена наоборот повысилась, это поле затрагивать не нужно.\n        ВАЖНО! Цена которую заплатит клиент указывается в поле "Цена", не перепутать!', verbose_name='Старая цена (для акций или распродаж)')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Изменен')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='mainstoreapp.category')),
                ('compatible', models.ManyToManyField(blank=True, related_name='models', to='mainstoreapp.CompatibleParts')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Публикация')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainstoreapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции/й',
                'ordering': ['title'],
            },
        ),
    ]
