# Generated by Django 3.2.9 on 2021-11-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0002_alter_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpost',
            name='is_publish',
            field=models.BooleanField(default=False, help_text='В публикации должен быть лишь 1 пост, иначе содержание на страничке\n                                     рискует превратиться в кашу', verbose_name='Публикация'),
        ),
        migrations.AddField(
            model_name='fixedpost',
            name='title',
            field=models.CharField(default='Без названия', help_text='Это поле описания поста, оно не будет фигурировать на страничке, оно нужно лишь\n                             для удобства поиска нужного, тк они буду сохраняться в базе данных и в случае необходимости,\n                             можно будет просто включать публикацию ранее написанного поста', max_length=250, verbose_name='Описание'),
        ),
    ]
