# Generated by Django 3.2.9 on 2021-11-24 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0003_auto_20211125_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedpost',
            old_name='is_publish',
            new_name='is_published',
        ),
    ]
