# Generated by Django 3.2.9 on 2021-11-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0004_rename_is_publish_fixedpost_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_category/%Y/%m/%d/'),
        ),
    ]
