# Generated by Django 3.2.9 on 2021-12-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0005_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='photos_category/%Y/%m/%d/'),
        ),
    ]
