# Generated by Django 3.2.9 on 2021-12-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0007_auto_20211202_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpost',
            name='photo',
            field=models.ImageField(blank=True, upload_to='backgrounds/%Y/%m/%d/'),
        ),
    ]
