# Generated by Django 3.2.9 on 2021-12-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0008_fixedpost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_offer',
            field=models.BooleanField(default=False, help_text='\n    При активации данного поля товар попадает в список " спецпредложений ", которые отображются в бургере ', verbose_name='Спецпрелдожение'),
        ),
    ]
