# Generated by Django 3.2.9 on 2021-12-15 01:58

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0010_auto_20211209_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='mainstoreapp.category', verbose_name='Категория'),
        ),
    ]
