# Generated by Django 3.2.9 on 2021-12-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0014_product_wholesale_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Поле для отображения старой цена. Для заполнения не обязательно. В случае если\n        цена на товар снижена, указать сюда старую цена а поле "Цена" указать новую, в таком случае на сайте старый \n        ценник будет перечеркнут. В случае если цена наоборот повысилась, это поле затрагивать не нужно.\n        ВАЖНО! Цена которую заплатит клиент указывается в поле "Цена", не перепутать!', max_digits=10, null=True, verbose_name='Старая цена (для акций или распродаж)'),
        ),
    ]
