# Generated by Django 3.2.9 on 2021-12-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0015_auto_20211220_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wholesale',
            field=models.BooleanField(default=False, verbose_name='Оптовик'),
        ),
    ]
