# Generated by Django 3.2.9 on 2021-12-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0016_alter_profile_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default='True', help_text='Это поле регулируется автоматически', verbose_name='В наличии'),
        ),
    ]
