# Generated by Django 3.2.9 on 2021-12-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0017_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default='in_stock_method()', help_text='Это поле регулируется автоматически', verbose_name='В наличии'),
        ),
    ]
