# Generated by Django 3.2.9 on 2021-12-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0020_remove_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdek_delivery_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доставка "сдек"')),
                ('poshta_delivery_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доставка "почта"')),
                ('min_sum_for_wholesale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная цена для оптовика')),
            ],
            options={
                'verbose_name': 'Цена(Доставка и Мин. для оптовика)',
                'verbose_name_plural': 'Цены(Доставка и Мин. для оптовика)',
            },
        ),
    ]
