# Generated by Django 3.2.9 on 2021-12-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0021_order_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена (Доставка и Мин. сумма для оптовика)', 'verbose_name_plural': 'Цены (Доставка и Мин. сумма для оптовика)'},
        ),
    ]
