# Generated by Django 3.2.9 on 2022-01-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0022_auto_20211224_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('promo', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды/ов',
            },
        ),
    ]
