# Generated by Django 3.2.9 on 2022-01-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0023_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Это поле варьируется автоматически,\n    если остаток больше 0 то оно активно, в случае если равно 0, доступность снимается. Поле нужно для \n    правильной фильтрафии товаров', verbose_name='Доступен'),
        ),
    ]
