# Generated by Django 3.2.9 on 2022-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0024_alter_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cdek_adress',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес пункта выдачи сдек'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pochta_adress',
            field=models.CharField(blank=True, max_length=250, verbose_name='Адрес для доставки на Почту России'),
        ),
    ]
