# Generated by Django 3.2.9 on 2022-01-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0025_auto_20220108_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cdek_adress',
            new_name='cdek_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pochta_adress',
            new_name='pochta_address',
        ),
    ]
