# Generated by Django 3.2.9 on 2022-01-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0026_auto_20220108_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='type_of_promo',
            field=models.CharField(choices=[('DISCOUNT', 'Скидка'), ('BUYER_TYPE', 'Выдача статуса оптового покупателя')], default='DISCOUNT', max_length=25),
        ),
    ]
