# Generated by Django 3.2.9 on 2022-01-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0027_promocode_type_of_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(default=0, help_text='Поле для промокода \n    скидок, обязательно только для промокодов дающие скидку на корзину. Значение которое будет установлено это процент,\n     который скинется пользувателю в общей суммы.', max_length=2, verbose_name='Скидка в %'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='type_of_promo',
            field=models.CharField(choices=[('DISCOUNT', 'Скидка'), ('BUYER_TYPE', 'Выдача статуса оптового покупателя')], default='DISCOUNT', max_length=25, verbose_name='тип промокода'),
        ),
    ]
