# Generated by Django 3.2.9 on 2022-01-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0028_auto_20220112_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='slug',
        ),
    ]
