# Generated by Django 3.2.9 on 2022-01-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0030_alter_promocode_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(blank=True, default=0, help_text='Поле для промокода \n    скидок, обязательно только для промокодов дающие скидку на корзину. Значение которое будет установлено это процент,\n     который скинется пользувателю в общей суммы.', null=True, verbose_name='Скидка в %'),
        ),
    ]
