# Generated by Django 3.2.9 on 2022-01-23 11:18

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0035_auto_20220119_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainstoreapp.category', verbose_name='Связи/ Категория/ Подкатегория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mainstoreapp.category', verbose_name='Категория'),
        ),
    ]
