# Generated by Django 3.2.9 on 2022-04-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0037_auto_20220425_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderbanner',
            name='type_post',
            field=models.CharField(choices=[('SLIDER', 'Разместить в слайдере'), ('FIXED_POST', 'Разместить в фиксированном посте (можно только 1)')], default='SLIDER', max_length=25, verbose_name='Где расположить объявление'),
        ),
    ]
