# Generated by Django 3.2.9 on 2022-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0039_auto_20220425_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='#', help_text='Ссылка которая при клике будет куда то уводить пользователя', max_length=250, verbose_name='Описание')),
                ('answer', models.CharField(default='#', help_text='Ссылка которая при клике будет куда то уводить пользователя', max_length=250, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
