# Generated by Django 3.2.9 on 2022-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0043_auto_20220427_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='Номер зарака'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.TextField(default='none', max_length=250, verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='message_text',
            field=models.TextField(default='none', max_length=250, verbose_name='сообщение пользователю'),
        ),
    ]
