# Generated by Django 3.2.9 on 2022-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0044_auto_20220427_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discont',
            field=models.IntegerField(default=0, verbose_name='скидка'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.IntegerField(default=0, verbose_name='общая сумма'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_delivery',
            field=models.CharField(choices=[('CDEK', 'СДЭК'), ('POCHTA', 'Почта РФ')], default='POCHTA', max_length=25, verbose_name='тип доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='Номер заказа'),
        ),
    ]
