# Generated by Django 3.2.9 on 2022-04-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0046_auto_20220427_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discont',
        ),
    ]
