# Generated by Django 3.2.9 on 2022-04-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0049_auto_20220427_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Тут указывает текст, который будет отправлен покупателю по sms и email.\n    После сообщения в автоматическом режиме будет довлено номер заказа и сумма заказа для пользователя', verbose_name='Инструкция по оплате')),
            ],
            options={
                'verbose_name': 'Инструкция для покупателя',
                'verbose_name_plural': 'Инструкция для покупателя',
            },
        ),
    ]
