# Generated by Django 3.2.9 on 2022-04-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0050_ordertext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='message_text',
        ),
    ]
