# Generated by Django 3.2.9 on 2022-04-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0051_remove_order_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='send_has_done',
        ),
        migrations.AddField(
            model_name='order',
            name='close',
            field=models.BooleanField(default=False, verbose_name='отменить заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('MANUAL', 'Сообщения с инструкцией отправлены'), ('TRACK', 'Оплата поступила, сообщения с треком отправлены'), ('CLOSE', 'Заказ закрыт'), ('CANCEL', 'Заказ отменен')], default='MANUAL', max_length=50, verbose_name='статус заказа'),
        ),
    ]
