# Generated by Django 3.2.9 on 2022-04-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0052_auto_20220430_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertext',
            name='email',
            field=models.EmailField(default='none', max_length=50, verbose_name='Почта на которую будет приходить уведомление о заказах'),
        ),
        migrations.AlterField(
            model_name='order',
            name='close',
            field=models.BooleanField(default=False, help_text='Отметить галку и нажми "сохранить" \n    и тогда заказ будет закрыт а товары которые в нем числятся уйдут обратно в продажу.', verbose_name='отменить заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='send',
            field=models.BooleanField(default=False, help_text='Укажи трек номер, поставь галку "отправить" \n    и нажми "сохранить". Тогда автоматически сообщение будет отправлено пользователю на номер телефона и почту с указанием трек номера.', verbose_name='отправить сообщение пользователю'),
        ),
    ]
