# Generated by Django 3.2.9 on 2022-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0053_auto_20220430_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertext',
            name='description',
        ),
        migrations.AddField(
            model_name='ordertext',
            name='details',
            field=models.TextField(default='none', help_text='Указание реквизитов для оплаты', verbose_name='Сообщение к реквизитами для оплаты'),
        ),
        migrations.AddField(
            model_name='ordertext',
            name='first_info',
            field=models.TextField(default='none', help_text='Первое сообщение которое будет выслано пользователю сразу после\n    оформления им заказа', verbose_name='Первое сообщение после оформления заказа'),
        ),
        migrations.AddField(
            model_name='ordertext',
            name='paid_for',
            field=models.TextField(default='none', help_text='Что то вроде "заказ оплачен, ожидает отправки"', verbose_name='Подтверждение оплаченого заказа'),
        ),
        migrations.AddField(
            model_name='ordertext',
            name='sent_by',
            field=models.TextField(default='none', help_text='Сообщение об отправке с трек номером. Трек номер в шаблоне\n    подставлять не нужно, его следует указывать в самом заказе', verbose_name='Последнее сообщение с данными отправки'),
        ),
    ]
