# Generated by Django 3.2.9 on 2022-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0054_auto_20220430_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertext',
            name='details',
            field=models.TextField(default='$', help_text='Указание реквизитов для оплаты. В этом поле нужно будет указать место для подстановки \n    суммы заказа, она встанет автоматически, достаточно только указать место для подставноки символом $', verbose_name='Сообщение к реквизитами для оплаты'),
        ),
        migrations.AlterField(
            model_name='ordertext',
            name='first_info',
            field=models.TextField(default='&', help_text='Первое сообщение которое будет выслано пользователю сразу после\n    оформления им заказа. В этом поле нужно будет указать место установки номера заказа, этот номер будет подставляться автоматически. Достаточно \n    указать символ & в месте, где нужно указать номер заказа', verbose_name='Первое сообщение после оформления заказа'),
        ),
        migrations.AlterField(
            model_name='ordertext',
            name='paid_for',
            field=models.TextField(default='& - $', help_text='Что то вроде "заказ оплачен, ожидает отправки. Нужно указать место подстановки номера заказа \n    и суммы заказа с помощью символов & и $ соответственно"', verbose_name='Подтверждение оплаченого заказа'),
        ),
        migrations.AlterField(
            model_name='ordertext',
            name='sent_by',
            field=models.TextField(default='%', help_text='Сообщение об отправке с трек номером. Трек номер в шаблоне\n    подставлять не нужно, его следует указывать в самом заказе. Тут нужно будет указать место установки транспортной службы. "Товар отправлен \n    транспортной службой ... трек номер - ... . Достаточно указать символ % в место куда нужно подставить транспортную службу. \n    Подставится автоматически , CDEK или Почта России а зависимости от выбранного покупателем. "', verbose_name='Последнее сообщение с данными отправки'),
        ),
    ]
