# Generated by Django 3.2.9 on 2022-04-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0055_auto_20220430_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send_first',
            field=models.BooleanField(default=False, help_text='Отправит сообщение с данными для перевода.', verbose_name='отправить сообщение с подтверждением оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='send_second',
            field=models.BooleanField(default=False, help_text='Отправит сообщение с подтверждением оплаты.', verbose_name='отправить сообщение с данными доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='send',
            field=models.BooleanField(default=False, help_text='Укажи трек номер, поставь галку "отправить" \n        и нажми "сохранить". Тогда автоматически сообщение будет отправлено пользователю на номер телефона и почту с указанием трек номера.', verbose_name='отправить сообщение с реквизитами'),
        ),
    ]
