# Generated by Django 3.2.9 on 2022-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0056_auto_20220430_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertext',
            name='title',
            field=models.CharField(default='none', max_length=100, verbose_name='Тема письма которая указывается при отправке письма покупателю'),
        ),
        migrations.AddField(
            model_name='profile',
            name='purchased',
            field=models.JSONField(default={}, verbose_name='Купленные товары'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('MANUAL', 'Сообщение с оповещением отправлено о заказе'), ('INVOICE', 'Сообщение с реквизитами отправлено'), ('PAYMENT', 'Сообщение с оповещением об оплате отправлено'), ('TRACK', 'Сообщение с треком отправлены'), ('CLOSE', 'Заказ закрыт'), ('CANCEL', 'Заказ отменен')], default='MANUAL', max_length=50, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='ordertext',
            name='sent_by',
            field=models.TextField(default='%', help_text='Сообщение об отправке с трек номером. Для указания трек номера в каком\n      либо месте сообщшения достаточно указать @, а для указания службы доставки указать знак % .\n      Например "Товар отправле службой % . Трек номер отправления @""', verbose_name='Последнее сообщение с данными отправки'),
        ),
    ]
