# Generated by Django 3.2.9 on 2022-05-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0057_auto_20220501_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='purchased',
            field=models.JSONField(verbose_name='Купленные товары'),
        ),
    ]
