# Generated by Django 3.2.9 on 2022-05-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0063_auto_20220504_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.CharField(max_length=240, unique=True, verbose_name='Промокод')),
                ('odnoklassniki', models.CharField(max_length=240, unique=True, verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Социалки',
                'verbose_name_plural': 'Социалок',
            },
        ),
    ]
