# Generated by Django 3.2.9 on 2022-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0064_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Социалки', 'verbose_name_plural': 'Социалки'},
        ),
        migrations.AlterField(
            model_name='social',
            name='odnoklassniki',
            field=models.CharField(default='#', max_length=240, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='social',
            name='vk',
            field=models.CharField(default='#', max_length=240, unique=True, verbose_name='Промокод'),
        ),
    ]
