# Generated by Django 3.2.9 on 2022-05-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0065_auto_20220505_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertext',
            name='email_server',
            field=models.EmailField(default='none', help_text='Данные поле не стоит трогать если на самом сервере, в настройка не изменены сообветствующие настройки', max_length=50, verbose_name='Это почта сервера, которая указывается как "отправитель" в рассылках.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Суммарный рейтинг'),
        ),
        migrations.AlterField(
            model_name='social',
            name='odnoklassniki',
            field=models.CharField(default='#', max_length=240, unique=True, verbose_name='ссылка на одноклассники'),
        ),
        migrations.AlterField(
            model_name='social',
            name='vk',
            field=models.CharField(default='#', max_length=240, unique=True, verbose_name='ссылка на вконтакте'),
        ),
    ]
