# Generated by Django 3.2.9 on 2022-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0067_remove_ordertext_email_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_time', models.CharField(max_length=250, unique=True, verbose_name='График работы')),
                ('phone', models.CharField(max_length=250, unique=True, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=250, unique=True, verbose_name='Почта')),
                ('address', models.CharField(max_length=250, unique=True, verbose_name='Адресс')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'График работы',
            },
        ),
    ]
