# Generated by Django 3.2.9 on 2022-05-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0068_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='work_time',
            field=models.TextField(max_length=250, unique=True, verbose_name='График работы'),
        ),
    ]
