# Generated by Django 3.2.9 on 2022-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0069_alter_contact_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='work_time',
            field=models.TextField(verbose_name='График работы'),
        ),
    ]
