# Generated by Django 3.2.9 on 2022-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0070_alter_contact_work_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_time',
            field=models.TextField(blank=True, verbose_name='График работы'),
        ),
    ]
