# Generated by Django 3.2.9 on 2022-05-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0073_alter_product_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verify',
            field=models.BooleanField(default=False, verbose_name='Подвтверждение почты'),
        ),
    ]
