# Generated by Django 3.2.9 on 2022-05-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0074_profile_email_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_verify',
            field=models.BooleanField(default=False, verbose_name='Подтверждение почты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purchased',
            field=models.JSONField(blank=True, default={}, verbose_name='Купленные товары'),
        ),
    ]
