# Generated by Django 3.2.9 on 2022-05-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0075_auto_20220508_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='glass',
            field=models.BooleanField(default=False, help_text='Этот флаг создан для товаров "стекла". Его активация\n    делает отображение товаров на страничке не сеткой а списком.', verbose_name='Стекло'),
        ),
    ]
