# Generated by Django 3.2.9 on 2022-05-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainstoreapp', '0076_product_glass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=250, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='sliderbanner',
            name='link',
            field=models.CharField(default='#', help_text='Ссылка которая при клике будет куда то уводить пользователя', max_length=250, verbose_name='Ссылка'),
        ),
    ]
